"""Draws the Android launcher icons and the launch-screen fridge from the web app's icon
(run after fridge/build.py; the APK workflow runs it too).

python3 fridge-app/make_icons.py
"""
import re
from pathlib import Path
from xml.etree import ElementTree as ET
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "fridge-app/android/app/src/main/res"
MASKABLE = Image.open(ROOT / "docs/fridge/icon-maskable-512.png").convert("RGBA")
DENSITIES = {"mdpi": 1, "hdpi": 1.5, "xhdpi": 2, "xxhdpi": 3, "xxxhdpi": 4}

for name, k in DENSITIES.items():
    out = RES / f"mipmap-{name}"
    out.mkdir(parents=True, exist_ok=True)
    # adaptive foreground: 108dp, the launcher crops it to its own shape (the fridge sits inside the 66dp safe zone)
    MASKABLE.resize((round(108 * k),) * 2, Image.LANCZOS).save(out / "ic_launcher_foreground.png")
    # legacy icons (Android 7 and older): 48dp, square with rounded corners and round
    n = round(48 * k)
    img = MASKABLE.resize((n, n), Image.LANCZOS)
    for file, draw in (("ic_launcher.png", lambda d: d.rounded_rectangle((0, 0, n - 1, n - 1), radius=n // 6, fill=255)),
                       ("ic_launcher_round.png", lambda d: d.ellipse((0, 0, n - 1, n - 1), fill=255))):
        mask = Image.new("L", (n, n), 0)
        draw(ImageDraw.Draw(mask))
        icon = Image.new("RGBA", (n, n), (0, 0, 0, 0))
        icon.paste(img, mask=mask)
        icon.save(out / file)

# launch screen: the icon's drawing (without its teal square) as a vector, 240dp wide in the 288dp
# launch-icon box, exactly where and how big the page's splash (fridge/index.html) starts
S, OFF = 240 / 512, 24
NS = "{http://www.w3.org/2000/svg}"


def rr(x, y, w, h, r):
    return (f"M{x + r},{y} H{x + w - r} A{r},{r} 0 0 1 {x + w},{y + r} V{y + h - r} A{r},{r} 0 0 1 {x + w - r},{y + h} "
            f"H{x + r} A{r},{r} 0 0 1 {x},{y + h - r} V{y + r} A{r},{r} 0 0 1 {x + r},{y} Z")


def ell(cx, cy, rx, ry):
    return f"M{cx - rx},{cy} A{rx},{ry} 0 1 0 {cx + rx},{cy} A{rx},{ry} 0 1 0 {cx - rx},{cy} Z"


paths = []
for el in ET.parse(ROOT / "fridge/assets/icon.svg").getroot().iter():
    tag, a = el.tag.replace(NS, ""), el.attrib
    f = lambda k, d=0: float(a.get(k, d))
    if tag == "rect":
        if a.get("width") == "512":
            continue   # the teal square is the launch screen's own background
        d = rr(f("x"), f("y"), f("width"), f("height"), f("rx"))
    elif tag == "circle":
        d = ell(f("cx"), f("cy"), f("r"), f("r"))
    elif tag == "ellipse":
        d = ell(f("cx"), f("cy"), f("rx"), f("ry"))
    elif tag == "path":
        d = a["d"]
    else:
        continue
    attrs = [f'android:pathData="{d}"']
    fill = a.get("fill")
    if fill and fill != "none":
        attrs.append(f'android:fillColor="{fill}"')
        if "opacity" in a:
            attrs.append(f'android:fillAlpha="{a["opacity"]}"')
    if a.get("stroke"):
        attrs += [f'android:strokeColor="{a["stroke"]}"', f'android:strokeWidth="{a.get("stroke-width", "1")}"']
        if a.get("stroke-linecap"):
            attrs.append(f'android:strokeLineCap="{a["stroke-linecap"]}"')
    paths.append("        <path " + " ".join(attrs) + " />")
xml = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- generated by fridge-app/make_icons.py from fridge/assets/icon.svg: the launch screen's fridge -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="288dp" android:height="288dp" android:viewportWidth="288" android:viewportHeight="288">
    <group android:translateX="{OFF}" android:translateY="{OFF}" android:scaleX="{S}" android:scaleY="{S}">
{chr(10).join(paths)}
    </group>
</vector>
"""
(RES / "drawable/splash_fridge.xml").write_text(xml, encoding="utf-8")
print("icons drawn")
